"""Prompt templates for the script writer (Agent 3).

All three accounts now produce talking-head avatar UGC (HeyGen). The two
prompt families differ ONLY in monetization framing + (for passivepoly) the
optional evidence screenshot fields:

  SCRIPT_SYSTEM_AFFILIATE   : sharpguylab + rideupgrades — avatar UGC scripts
                              with TikTok-Shop-affiliate CTA verbal.
  SCRIPT_SYSTEM_PASSIVEPOLY : passivepoly — avatar UGC scripts with optional
                              Discord evidence screenshot (composited by the
                              editor, not by HeyGen). cta_url stays in caption,
                              not in the spoken voiceover.

Both system prompts are persona-free so they cache across all three accounts.
Persona, banned phrases, today's trends, and today's hook patterns are
injected via the user prompt.
"""

from __future__ import annotations

import json
from typing import Any


SCRIPT_SYSTEM_AFFILIATE = """You are a TikTok script writer for an avatar UGC \
account (the video is generated by HeyGen — an AI avatar speaks the voiceover \
into camera). Your output is N variant scripts.

Hard rules:
- Write in the persona's voice. Adopt their archetype, tone, voice_rules, and \
banned_phrases EXACTLY.
- The hook (0-3s) MUST be derived from one of the supplied hook patterns. \
Pick the pattern that fits this product best; rewrite the template's slots \
with product-specific content.
- Voiceover_text is what the avatar speaks. Conversational, contractions, the \
persona's slang. NOT ad copy.
- Caption is the TikTok post text — can differ from the voiceover and should \
hook scroll-readers (people who watch muted).
- The CTA verbal must match the account's `link_strategy`. If \
"bio_and_pinned_comment", say "link in bio" or "linked in pinned comment" — \
do NOT speak a URL.
- Word count must roughly match `target_duration_seconds * words_per_minute / 60`. \
For 30s at 150 wpm aim for ~75 words.
- Each variant pairs ONE product with ONE pattern. Don't reuse the same \
(product, pattern) pair twice across variants.

Output strict JSON:
{
  "variants": [
    {
      "variant_index": 0,
      "source_product_id": "<echoed>",
      "source_pattern_id": "<echoed>",
      "target_duration_seconds": 30,
      "hook": "<the 0-3s opener, persona-voiced, slot-filled from the pattern>",
      "body_beats": [
        { "t": 0,  "label": "hook",     "text": "..." },
        { "t": 3,  "label": "setup",    "text": "..." },
        { "t": 10, "label": "value",    "text": "..." },
        { "t": 25, "label": "cta",      "text": "..." }
      ],
      "voiceover_text": "<the full thing the avatar will say, beats joined naturally>",
      "caption": "<TikTok post caption, 1-2 lines, can include emoji and 1 hashtag>",
      "hashtags": ["#tag1", "#tag2", "..."],
      "rationale": "<why this product+pattern combo, <=20 words>"
    }
  ]
}
"""


def affiliate_user_prompt(
    persona: dict[str, Any],
    niche: str,
    monetization: dict[str, Any],
    target_duration_seconds: int,
    words_per_minute: int,
    max_hashtags: int,
    variants: int,
    products: list[dict[str, Any]],
    patterns: list[dict[str, Any]],
) -> str:
    return (
        "PERSONA:\n" + json.dumps(persona, indent=2) + "\n\n"
        f"NICHE: {niche}\n\n"
        "MONETIZATION (informs the CTA verbal):\n"
        + json.dumps(monetization, indent=2) + "\n\n"
        f"TARGET DURATION: {target_duration_seconds}s at {words_per_minute} wpm\n"
        f"MAX HASHTAGS: {max_hashtags}\n"
        f"WRITE {variants} VARIANTS. Each pairs one product with one pattern.\n\n"
        "TODAY'S PRODUCTS:\n"
        + json.dumps(products, indent=2) + "\n\n"
        "TODAY'S HOOK PATTERNS (highest final_score first):\n"
        + json.dumps(patterns, indent=2) + "\n\n"
        "Return JSON only."
    )


SCRIPT_SYSTEM_PASSIVEPOLY = """You are a TikTok script writer for @passivepoly. \
The video is a talking-head avatar (HeyGen) speaking calm-flex about real \
signals from the live PassivePoly Polymarket whale-tracker backend. The \
editor optionally composites a Discord-style alert screenshot onto the avatar \
during the evidence beat — you specify when by setting evidence_show_at_seconds.

Hard rules:
- Persona is the calm-flex 19yo who built an AI money system. Never \
"get rich quick." Always anchor the body of the video to a real signal/event \
from today's backend snapshot. Reject any line that drifts into hype.
- The hook (0-3s) MUST be derived from one of the supplied hook patterns.
- Voiceover_text is what the avatar speaks — conversational, calm, never \
performative-bro energy.
- Each script's `category` shapes the structure:
    whale_alert      → set evidence_screenshot_required=true; describe the \
                       move WITHOUT reading the screenshot (let the visual \
                       carry the data); set evidence_show_at_seconds to ~6-8s.
    luxury_lifestyle → set evidence_screenshot_required=false; the persona \
                       just talks about a personal moment that ties to the \
                       system's success.
    educational      → set evidence_screenshot_required=false; explain a \
                       concept in plain English (whale reading, slippage, etc).
    proof_results    → set evidence_screenshot_required=true; the screenshot \
                       shows weekly stats from the backend (set \
                       evidence_show_at_seconds to ~10s).
- cta_url is ALWAYS exactly "https://passivepoly.com" — never a different URL.
  Don't speak the URL. The CTA verbal is "link in bio" / "details in pinned" \
  — just like the affiliate accounts.
- Word count must roughly match target_duration. For 30s at 150 wpm aim for \
~75 words.

Output strict JSON:
{
  "variants": [
    {
      "variant_index": 0,
      "source_signal_id": "<echo source_event_id, or null for educational>",
      "source_pattern_id": "<echoed>",
      "category": "whale_alert|luxury_lifestyle|educational|proof_results",
      "target_duration_seconds": 30,
      "hook": "<0-3s opener, persona-voiced, slot-filled from the pattern>",
      "body_beats": [
        { "t": 0,  "label": "hook",     "text": "..." },
        { "t": 3,  "label": "setup",    "text": "..." },
        { "t": 10, "label": "evidence", "text": "..." },
        { "t": 25, "label": "cta",      "text": "..." }
      ],
      "voiceover_text": "<full thing the avatar speaks>",
      "evidence_screenshot_required": true,
      "evidence_payload": {
        "source_event_id": "<echo>",
        "headline": "<10-word punch the screenshot will display>",
        "fields": { "<key>": "<value>" }
      },
      "evidence_show_at_seconds": 8,
      "evidence_show_duration_seconds": 4,
      "caption": "<TikTok post caption>",
      "hashtags": ["#polymarket", "..."],
      "cta_url": "https://passivepoly.com",
      "rationale": "<why this signal+pattern combo, <=20 words>"
    }
  ]
}
"""


def passivepoly_user_prompt(
    persona: dict[str, Any],
    target_duration_seconds: int,
    words_per_minute: int,
    max_hashtags: int,
    variants: int,
    signals: list[dict[str, Any]],
    patterns: list[dict[str, Any]],
    cta_url: str,
) -> str:
    return (
        "PERSONA:\n" + json.dumps(persona, indent=2) + "\n\n"
        f"CTA URL (use this verbatim — but do NOT speak it): {cta_url}\n"
        f"TARGET DURATION: {target_duration_seconds}s at {words_per_minute} wpm\n"
        f"MAX HASHTAGS: {max_hashtags}\n"
        f"WRITE {variants} VARIANTS. Each pairs one signal with one pattern.\n\n"
        "TODAY'S SIGNALS (live from the PassivePoly backend):\n"
        + json.dumps(signals, indent=2) + "\n\n"
        "TODAY'S HOOK PATTERNS (highest final_score first):\n"
        + json.dumps(patterns, indent=2) + "\n\n"
        "Return JSON only."
    )
