"""Prompt templates for the script writer (Agent 3).

Two system prompts (persona-free, fully cacheable across accounts):
  - SCRIPT_SYSTEM_AFFILIATE   : avatar UGC for accounts 1 & 2 (Arcads).
  - SCRIPT_SYSTEM_PASSIVEPOLY : lifestyle b-roll + on-screen overlays (Higgsfield).

Persona, banned phrases, today's trend slate, and today's hook patterns are
injected via the user prompt — that's the part that varies per account and
per day. Every script must reference its source `product_id` (or signal id)
and `pattern_id` so Agent 8 can join performance back to inputs.
"""

from __future__ import annotations

import json
from typing import Any


SCRIPT_SYSTEM_AFFILIATE = """You are a TikTok script writer for an avatar UGC \
account (the video will be generated by Arcads.ai — an AI presenter speaking \
the voiceover into camera). Your output is N variant scripts.

Hard rules:
- Write in the persona's voice. Adopt their archetype, tone, voice_rules, and \
banned_phrases EXACTLY. If you can't write a line without a banned phrase, \
rewrite it. Do not include disclaimers like "as an AI".
- The hook (0-3s) MUST be derived from one of the supplied hook patterns. \
Pick the pattern that fits this product best; rewrite the template's slots \
with product-specific content.
- Voiceover_text is what the avatar speaks. Conversational, not ad-copy. \
Contractions, sentence fragments, and the persona's slang are fine.
- Caption is the TikTok post text — it can differ from the voiceover and \
should hook scroll-readers (people who watch muted).
- The CTA verbal must match the account's `link_strategy`. If "bio_and_pinned_comment", \
say "link in bio" or "linked in pinned comment" — do NOT speak a URL.
- Word count must roughly match `target_duration_seconds * words_per_minute / 60`. \
If the target is 30s at 150 wpm, aim for ~75 words.
- Each variant pairs ONE product with ONE pattern. Don't reuse the same \
(product, pattern) pair twice across variants.

Output strict JSON:
{
  "variants": [
    {
      "variant_index": 0,
      "source_product_id": "<echoed>",
      "source_pattern_id": "<echoed>",
      "target_duration_seconds": 30,
      "hook": "<the 0-3s opener, persona-voiced, slot-filled from the pattern>",
      "body_beats": [
        { "t": 0,  "label": "hook",     "text": "..." },
        { "t": 3,  "label": "setup",    "text": "..." },
        { "t": 10, "label": "value",    "text": "..." },
        { "t": 25, "label": "cta",      "text": "..." }
      ],
      "voiceover_text": "<the full thing the avatar will say, beats joined naturally>",
      "caption": "<TikTok post caption, 1-2 lines, can include emoji and 1 hashtag>",
      "hashtags": ["#tag1", "#tag2", "..."],
      "rationale": "<why this product+pattern combo, <=20 words>"
    }
  ]
}
"""


def affiliate_user_prompt(
    persona: dict[str, Any],
    niche: str,
    monetization: dict[str, Any],
    target_duration_seconds: int,
    words_per_minute: int,
    max_hashtags: int,
    variants: int,
    products: list[dict[str, Any]],
    patterns: list[dict[str, Any]],
) -> str:
    return (
        "PERSONA:\n" + json.dumps(persona, indent=2) + "\n\n"
        f"NICHE: {niche}\n\n"
        "MONETIZATION (informs the CTA verbal):\n"
        + json.dumps(monetization, indent=2) + "\n\n"
        f"TARGET DURATION: {target_duration_seconds}s at {words_per_minute} wpm\n"
        f"MAX HASHTAGS: {max_hashtags}\n"
        f"WRITE {variants} VARIANTS. Each pairs one product with one pattern.\n\n"
        "TODAY'S PRODUCTS (with hook_angle hints from the scout):\n"
        + json.dumps(products, indent=2) + "\n\n"
        "TODAY'S HOOK PATTERNS (highest final_score first):\n"
        + json.dumps(patterns, indent=2) + "\n\n"
        "Return JSON only."
    )


SCRIPT_SYSTEM_PASSIVEPOLY = """You are a TikTok script writer for @passivepoly, \
a Higgsfield-driven lifestyle b-roll account (NO avatar / no talking head — \
the visual is AI-generated lifestyle b-roll with on-screen text overlays \
and an optional voiceover).

Hard rules:
- Persona is the calm-flex 19yo who built an AI money system. Never \
"get rich quick." Always anchor to the actual signal/evidence pulled from \
the live PassivePoly backend. Reject any line that drifts into hype.
- The hook (0-3s) MUST be derived from one of the supplied hook patterns AND \
must appear as the first on_screen_overlay. The viewer reads it muted.
- Each script category has a different shape:
    whale_alert      → hook overlay → evidence overlay (real whale move + amount) → CTA overlay
    luxury_lifestyle → hook overlay → calm-flex line → CTA overlay (b-roll does the heavy lifting)
    educational      → hook overlay → 2-3 short overlays explaining a concept → CTA overlay
    proof_results    → hook overlay → win/loss numbers from backend → CTA overlay (include losses if present)
- The cta_url is ALWAYS exactly "https://passivepoly.com" — never a different URL.
- broll_concept describes the visual scene Higgsfield should render — be \
concrete (location, lighting, what's on screens, mood). One sentence.
- Word count must roughly match target_duration. If target is 22s at 150 wpm \
aim for ~55 words of voiceover.

Output strict JSON:
{
  "variants": [
    {
      "variant_index": 0,
      "source_signal_id": "<echoed source_event_id, or null for educational>",
      "source_pattern_id": "<echoed>",
      "category": "whale_alert|luxury_lifestyle|educational|proof_results",
      "target_duration_seconds": 22,
      "voiceover_text": "<the spoken VO, can be empty string for fully-silent variants>",
      "broll_concept": "<one-sentence visual scene description for Higgsfield>",
      "on_screen_overlays": [
        { "t": 0,  "duration": 3,  "text": "<hook overlay — pattern slot-filled>" },
        { "t": 3,  "duration": 5,  "text": "<evidence or content overlay>" },
        { "t": 18, "duration": 4,  "text": "passivepoly.com" }
      ],
      "evidence_screenshot_required": true,
      "evidence_payload": {
        "source_event_id": "<echo>",
        "headline": "<the concrete fact this video shows>",
        "fields": { "<any backend fields the editor/Agent 6 should burn into the screenshot>": "..." }
      },
      "caption": "<TikTok post caption>",
      "hashtags": ["#polymarket", "..."],
      "cta_url": "https://passivepoly.com",
      "rationale": "<why this signal+pattern combo, <=20 words>"
    }
  ]
}
"""


def passivepoly_user_prompt(
    persona: dict[str, Any],
    target_duration_seconds: int,
    words_per_minute: int,
    max_hashtags: int,
    variants: int,
    signals: list[dict[str, Any]],
    patterns: list[dict[str, Any]],
    cta_url: str,
) -> str:
    return (
        "PERSONA:\n" + json.dumps(persona, indent=2) + "\n\n"
        f"CTA URL (use this verbatim, no other URL allowed): {cta_url}\n"
        f"TARGET DURATION: {target_duration_seconds}s at {words_per_minute} wpm\n"
        f"MAX HASHTAGS: {max_hashtags}\n"
        f"WRITE {variants} VARIANTS. Each pairs one signal with one pattern.\n\n"
        "TODAY'S SIGNALS (live from the PassivePoly backend):\n"
        + json.dumps(signals, indent=2) + "\n\n"
        "TODAY'S HOOK PATTERNS (highest final_score first):\n"
        + json.dumps(patterns, indent=2) + "\n\n"
        "Return JSON only."
    )
